sonar.projectKey=burevestnik
sonar.projectName=burevestnik
sonar.projectVersion=0.1.0

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/.venv/**,**/.playwright-mcp/**,**/.idea/**,**/.git/**,**/__pycache__/**,**/*.jpeg,**/*.png,**/dist/**,**/build/**,tests/fixtures/**
sonar.test.exclusions=**/.venv/**,tests/fixtures/**

sonar.python.coverage.reportPaths=coverage.xml
